name: Deploy to Heroku - Container -

on:
  push:
    branches:
      - master
    paths:
      - "container/**"
      - ".github/workflows/container.yaml"

defaults:
  run:
    working-directory: container

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add module remote origin
        run: git remote add heroku-container https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Deploy module to Heroku
        run: git push heroku-container master
