name: Deploy to Heroku - Container -

on:
  push:
    branches:
      - master
    paths:
      - "container/**"
      - ".github/workflows/container.yaml"

# defaults:
#   run:
#     working-directory: container

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add module remote origin
        run: heroku git:remote -a container-mfe-module
      - name: Specify Buildpack
        run: heroku buildpacks:set heroku/nodejs
      - name: Deploy module to Heroku
        run: git subtree push --prefix container heroku master
